import fs from 'node:fs';import path from 'node:path';import Database from 'better-sqlite3';
export const DATA_CONTRACT_VERSION='alantu-v6-market-event-time-v1';
export const DATA_CONTRACT_TEXT='One market sample = one distinct observed (symbol, market_at_ms). market_at_ms is the sole model clock; received_at_ms/computed_at_ms are system metadata only. Duplicate timestamps do not increase sample count. Gaps remain gaps: no forward-fill, interpolation, synthetic zero-return, or poll-derived samples. delta_t_ms is the difference between consecutive actual market timestamps. Predictions use only observed events at or before entry market time; predicted points never become market inputs. Outcomes use only later observed events; if no acceptable real endpoint exists near target time the outcome is invalid. Every prediction stores its feature vector, feature summary, horizon, barrier, cost assumption, model version and evaluation contract for reproducibility.';
export function openMarketDb(file=process.env.ALANTU_SQLITE_PATH||'/data/alantu-market.sqlite'){
 fs.mkdirSync(path.dirname(file),{recursive:true});const db=new Database(file);db.pragma('journal_mode = WAL');db.pragma('synchronous = NORMAL');db.pragma('foreign_keys = ON');db.pragma('busy_timeout = 5000');
 db.exec(`
 CREATE TABLE IF NOT EXISTS contracts(contract_version TEXT PRIMARY KEY,contract_text TEXT NOT NULL,created_at_ms INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS market_events(id INTEGER PRIMARY KEY,symbol TEXT NOT NULL,market_at_ms INTEGER NOT NULL,received_at_ms INTEGER,price REAL NOT NULL,day_volume REAL,delta_volume REAL,source TEXT NOT NULL DEFAULT 'yahoo',contract_version TEXT NOT NULL,raw_json TEXT,inserted_at_ms INTEGER NOT NULL,UNIQUE(symbol,market_at_ms));
 CREATE INDEX IF NOT EXISTS market_events_symbol_time ON market_events(symbol,market_at_ms);
 CREATE TABLE IF NOT EXISTS predictions(id TEXT PRIMARY KEY,model_version TEXT NOT NULL,horizon_minutes INTEGER NOT NULL,entry_market_at_ms INTEGER NOT NULL,entry_received_at_ms INTEGER,target_market_at_ms INTEGER NOT NULL,entry_price REAL NOT NULL,structural_dir INTEGER,structural_score REAL,learned_dir INTEGER,p_up REAL,confidence REAL,model_n INTEGER,barrier_bps REAL,assumed_roundtrip_cost_bps REAL,gate_sample INTEGER NOT NULL DEFAULT 0,feature_vector_json TEXT NOT NULL,feature_summary_json TEXT,evaluation_contract TEXT NOT NULL,contract_version TEXT NOT NULL,contract_text TEXT NOT NULL,contract_json TEXT NOT NULL,computed_at_ms INTEGER NOT NULL,UNIQUE(model_version,horizon_minutes,entry_market_at_ms));
 CREATE INDEX IF NOT EXISTS predictions_entry_time ON predictions(entry_market_at_ms);
 CREATE TABLE IF NOT EXISTS outcomes(prediction_id TEXT PRIMARY KEY REFERENCES predictions(id),status TEXT NOT NULL,reason TEXT,evaluated_at_ms INTEGER NOT NULL,endpoint_market_at_ms INTEGER,endpoint_received_at_ms INTEGER,endpoint_price REAL,endpoint_return_bps REAL,timing_error_ms INTEGER,barrier_label INTEGER,barrier_at_ms INTEGER,mfe_bps REAL,mae_bps REAL,net_return_bps REAL,correct INTEGER,raw_json TEXT NOT NULL);
 `);
 db.prepare('INSERT OR IGNORE INTO contracts VALUES(?,?,?)').run(DATA_CONTRACT_VERSION,DATA_CONTRACT_TEXT,Date.now());
 const event=db.prepare(`INSERT INTO market_events(symbol,market_at_ms,received_at_ms,price,day_volume,delta_volume,source,contract_version,raw_json,inserted_at_ms) VALUES(@symbol,@market_at_ms,@received_at_ms,@price,@day_volume,@delta_volume,@source,@contract_version,@raw_json,@inserted_at_ms) ON CONFLICT(symbol,market_at_ms) DO UPDATE SET received_at_ms=MAX(COALESCE(market_events.received_at_ms,0),COALESCE(excluded.received_at_ms,0)),day_volume=MAX(COALESCE(market_events.day_volume,0),COALESCE(excluded.day_volume,0)),delta_volume=MAX(COALESCE(market_events.delta_volume,0),COALESCE(excluded.delta_volume,0)),raw_json=excluded.raw_json`);
 const pred=db.prepare(`INSERT OR IGNORE INTO predictions(id,model_version,horizon_minutes,entry_market_at_ms,entry_received_at_ms,target_market_at_ms,entry_price,structural_dir,structural_score,learned_dir,p_up,confidence,model_n,barrier_bps,assumed_roundtrip_cost_bps,gate_sample,feature_vector_json,feature_summary_json,evaluation_contract,contract_version,contract_text,contract_json,computed_at_ms) VALUES(@id,@model_version,@horizon_minutes,@entry_market_at_ms,@entry_received_at_ms,@target_market_at_ms,@entry_price,@structural_dir,@structural_score,@learned_dir,@p_up,@confidence,@model_n,@barrier_bps,@assumed_roundtrip_cost_bps,@gate_sample,@feature_vector_json,@feature_summary_json,@evaluation_contract,@contract_version,@contract_text,@contract_json,@computed_at_ms)`);
 const outcome=db.prepare(`INSERT OR REPLACE INTO outcomes VALUES(@prediction_id,@status,@reason,@evaluated_at_ms,@endpoint_market_at_ms,@endpoint_received_at_ms,@endpoint_price,@endpoint_return_bps,@timing_error_ms,@barrier_label,@barrier_at_ms,@mfe_bps,@mae_bps,@net_return_bps,@correct,@raw_json)`);
 return {db,file,
 recordEvent(e){if(!(Number(e?.t)>0)||!(Number(e?.p)>0)||!e?.s)return;event.run({symbol:e.s,market_at_ms:+e.t,received_at_ms:Number.isFinite(+e.recv_at)?+e.recv_at:null,price:+e.p,day_volume:Number.isFinite(+e.day_volume)?+e.day_volume:null,delta_volume:Number.isFinite(+e.dv)?+e.dv:null,source:e.source||'yahoo',contract_version:DATA_CONTRACT_VERSION,raw_json:JSON.stringify(e),inserted_at_ms:Date.now()});},
 recordPrediction(p){const em=+(p.entry_market_ms||Date.parse(p.entry_market_at)),tm=Date.parse(p.target_at),er=Date.parse(p.entry_received_at),cj={contract_version:DATA_CONTRACT_VERSION,model_version:p.version,horizon_minutes:p.horizon_minutes,clock:'market_event_time',entry_market_at_ms:em,target_market_at_ms:tm,feature_vector:p.feature_vector,feature_summary:p.feature_summary,barrier_bps:p.barrier_bps,assumed_roundtrip_cost_bps:p.assumed_roundtrip_cost_bps,evaluation_contract:p.evaluation_contract};pred.run({id:p.id,model_version:p.version,horizon_minutes:p.horizon_minutes,entry_market_at_ms:em,entry_received_at_ms:Number.isFinite(er)?er:null,target_market_at_ms:tm,entry_price:p.entry_price,structural_dir:p.structural_dir??null,structural_score:p.structural_score??null,learned_dir:p.learned_dir??null,p_up:p.p_up??null,confidence:p.confidence??null,model_n:p.model_n??null,barrier_bps:p.barrier_bps??null,assumed_roundtrip_cost_bps:p.assumed_roundtrip_cost_bps??null,gate_sample:p.gate_sample?1:0,feature_vector_json:JSON.stringify(p.feature_vector||[]),feature_summary_json:JSON.stringify(p.feature_summary||{}),evaluation_contract:p.evaluation_contract,contract_version:DATA_CONTRACT_VERSION,contract_text:DATA_CONTRACT_TEXT,contract_json:JSON.stringify(cj),computed_at_ms:Date.now()});},
 recordOutcome(o){const pm=Date.parse(o.endpoint_market_at||o.endpoint_at),pr=Date.parse(o.endpoint_received_at),ba=Date.parse(o.barrier_at);outcome.run({prediction_id:o.id,status:o.status,reason:o.reason||null,evaluated_at_ms:Date.now(),endpoint_market_at_ms:Number.isFinite(pm)?pm:null,endpoint_received_at_ms:Number.isFinite(pr)?pr:null,endpoint_price:o.endpoint_price??null,endpoint_return_bps:o.endpoint_return_bps??null,timing_error_ms:o.timing_error_ms??null,barrier_label:o.barrier_label??null,barrier_at_ms:Number.isFinite(ba)?ba:null,mfe_bps:o.mfe_bps??null,mae_bps:o.mae_bps??null,net_return_bps:o.net_return_bps??null,correct:o.correct==null?null:(o.correct?1:0),raw_json:JSON.stringify(o)});},
 stats(){return {file,contract_version:DATA_CONTRACT_VERSION,events:db.prepare('SELECT COUNT(*) n FROM market_events').get().n,predictions:db.prepare('SELECT COUNT(*) n FROM predictions').get().n,outcomes:db.prepare('SELECT COUNT(*) n FROM outcomes').get().n};}};
}
